defaults:
  - backend: pytorch # default backend
  - benchmark: inference # default benchmark
  - base_config # inherits from base config
  - _self_ # for hydra 1.1 compatibility

experiment_name: bert-pytorch-inference-dtype(${backend.torch_dtype})-batch_size(${benchmark.input_shapes.batch_size})

model: bert-base-uncased
device: cuda

benchmark:
  memory: true

hydra:
  sweeper:
    params:
      backend.torch_dtype: float16,float32
      benchmark.input_shapes.batch_size: 1,16
