name: Benchmarks for Transformers+ROCm (nightly)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
    # every three hours

jobs:
  run-regression:
    runs-on: hf-amd-mi210-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build
          --file docker/rocm.dockerfile
          --build-arg USER_ID=$(id -u)
          --build-arg GROUP_ID=$(id -g)
          --build-arg ROCM_VERSION=5.6.1
          --tag opt-bench-rocm:5.6.1
          .

      - name: Run Benchmarks
        run: docker run
          --rm
          --device /dev/kfd
          --device /dev/dri
          --entrypoint /bin/bash
          --volume $(pwd):/workspace/optimum-amd
          --volume $HOME/.cache/huggingface:/home/user/.cache/huggingface
          --workdir /workspace/optimum-amd
          --env USE_ROCM="1"
          opt-bench-rocm:5.6.1
          -c "sh benchmarks/nightly.sh"
