name: Build PR documentation

on:
  pull_request:
    branches: [main]
    paths:
      - "optimum/**.py"
      - "docs/**"
      - ".github/workflows/build_pr_documentation.yml"
      - ".github/workflows/delete_doc_comment.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_documentation:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      PR_NUMBER: ${{ github.event.number }}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
      PR_CLONE_URL: ${{ github.event.pull_request.head.repo.clone_url }}

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Make documentation
        run: |
          make doc BUILD_DIR=./doc-build VERSION=pr_$PR_NUMBER
          sudo mv ./doc-build/optimum.amd ./doc-build/optimum-amd
          echo ${COMMIT_SHA} > ./commit_sha
          echo ${PR_NUMBER} > ./pr_number
        env:
          COMMIT_SHA_SUBPACKAGE: ${{ github.event.pull_request.head.sha }}

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: doc-build-artifact
          path: ./doc-build/optimum-amd
