# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Ryzen Modeling - Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: [self-hosted, single-npu, amd-npu, ryzenai]
    steps:
    - uses: actions/checkout@v2
    - name: Create and start a virtual environment
      run: |
        conda create --prefix venv --clone ryzenai-1.0.1-ci
    - name: Install dependencies
      run: |
        conda activate .\venv
        python -m pip install --upgrade pip
        pip install .[tests]
        pip install git+https://github.com/huggingface/optimum.git
    - name: Test with Pytest
      run: |
        conda activate .\venv
        pytest -s -v tests/ryzenai/test_modeling.py 
    - name: Cleanup
      run: |
        rm -r .\venv
      
